# Use a imagem oficial do MySQL
FROM mysql:8.0

# Define a senha do root user para "12345"
ENV MYSQL_ROOT_PASSWORD="12345"

# Cria um database chamado "testdb" ao iniciar o container
ENV MYSQL_DATABASE="testdb"

EXPOSE 3306


